app:
  env: dev
  name: Tiny Framework
  base_url:
  use_sessions:
  log_file: '%var_dir%/log/framework.log'

api:
  username:
  password:

middleware:
  dir: '%base_dir%/src/Middleware'
  namespace: Donchev\Framework\Middleware

db:
  host:
  name:
  username:
  password:
  port: 3306
  charset: utf8mb4

mail:
  host: smtp.mailtrap.io
  username:
  password:
  secure: null
  port: 2525
  from_name: 'Tiny Framework Mailer'
  from_email: